---
title: "sample_reprex"
author: "Mark Roman Miller"
date: "5/13/2020"
output: html_document
---

```{r}
library(tidyverse)
library(tibble)
library(vctrs)
library(zeallot)

# what's the vector ontology?
new_vector3 <- function(x=double(), y=double(), z=double()) {
  vec_assert(x, ptype=double())
  vec_assert(y, ptype=double())
  vec_assert(z, ptype=double())
  new_rcrd(list(x=x, y=y, z=z), class="vrm_vector3")
}

vector3 <- function(x, y, z) {
  c(x, y, z) %<-% vec_cast_common(x, y, z, .to=double())
  c(x, y, z) %<-% vec_recycle_common(x, y, z)
  new_vector3(x, y, z)
}

format.vrm_vector3 <- function(v, ...) {
  # TODO: keep width, etc in mind.
  x <- field(v, "x")
  y <- field(v, "y")
  z <- field(v, "z")

  out <- paste0("(", x, ", ", y, ", ", z, ")")
  out[is.na(x) | is.na(y) | is.na(z)] <- NA

  out
}

vec_ptype_abbr.vrm_vector3 <- function(x, ...) {
  "vct3"
}

sqrt_1_3 <- sqrt(1/3)

sample_table <- tibble(pos = vector3(c(1, 0, 0, sqrt_1_3), c(0, 1, 0, sqrt_1_3), c(0, 0, 1, sqrt_1_3)))

# in print.paged_df

print(sample_table)

print.foobar <- function(...) {
  print("Aef - building")
  cat("aef")
}

structure(1, class="foobar")

print(sample_table)
```











```{r render=normal_print}
library(rmarkdown)

knit_print.foo <- function(x, ...) {
  cat("foobar")
}

print.tbl_df <- function(x, ...) {
  print("fooobar")
  knitr::knit_print(x, ...)
}

print.foo <- function(x, ...) {
  print.data.frame(x, ...)
}

class(sample_table) <- c("foo", class(sample_table))


sample_table$pos$x


```
